#!/bin/sh
# Source tutorial run functions
python3 constant/circularCage.py
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication checkMesh

runApplication decomposePar
runApplication mpirun -np 8 fixedNetFoam -parallel
# runApplication reconstructPar
